name: FB UID Bot Auto
on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run bot
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          FB_TOKEN: ${{ secrets.FB_TOKEN }}
          CONCURRENCY: 6
          REQUEST_TIMEOUT: 10
        run: python bot.py
